//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSatisTakip.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Urun
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Urun()
        {
            this.tbl_Satis = new HashSet<tbl_Satis>();
        }
    
        public int urunId { get; set; }
        public Nullable<int> kategoriId { get; set; }
        public string urunAd { get; set; }
        public string marka { get; set; }
        public Nullable<decimal> fiyat { get; set; }
        public Nullable<int> stok { get; set; }
    
        public virtual tbl_Kategori tbl_Kategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Satis> tbl_Satis { get; set; }
    }
}
